## Google Play Store Apps Analysis

### Business Problem

The Google Play Store contains millions of applications across different categories. Understanding what contributes to successful applications can help developers and businesses make better decisions.

### Objectives

- Analyze the distribution of apps across categories.
- Identify factors affecting ratings.
- Study installs and pricing.
- Examine relationships between app size, category and popularity.
- Discover trends in user reviews.
- Provide business recommendations.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings("ignore")

In [ ]:
# LOADING DATASET

apps = pd.read_csv('../datasets/apps.csv')
reviews = pd.read_csv('../datasets/reviews.csv')

pd.set_option('display.max.rows', 1000)
pd.set_option('display.max.columns', 1000)

apps.head()
reviews.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [3]:
# INSPECTION OF DATASET
print('APP DATASET\nNo of rows =', apps.shape[0],'\nNo of columns =', apps.shape[1],'\n')
print('REVIEWS DATASET\nNo of rows =', reviews.shape[0],'\nNo of columns =', reviews.shape[1],'\n')

print('INSPECTING APPS DATASET\n')
print(apps.info())
print(apps.sample())

print('\nINSPECTING REVIEWS DATASET\n')
print(reviews.info())
print(reviews.sample())

APP DATASET
No of rows = 10841
No of columns = 13

REVIEWS DATASET
No of rows = 64295
No of columns = 5

INSPECTING APPS DATASET

<class 'pandas.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  str
 1   Category        10841 non-null  str
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  str
 4   Size            10841 non-null  str
 5   Installs        10841 non-null  str
 6   Type            10840 non-null  str
 7   Price           10841 non-null  str
 8   Content Rating  10840 non-null  str
 9   Genres          10841 non-null  str
 10  Last Updated    10841 non-null  str
 11  Current Ver     10833 non-null  str
 12  Android Ver     10838 non-null  str
dtypes: float64(1), str(12)
memory usage: 1.1 MB
None
              App Category  Rating Reviews  Size  Installs  Type Price  \
5146  Ah! Monster   FAMILY     4.1    1998  9.8M  100,000+  Free     0

     Content Rating  Genres   Last Updated Current Ver Android Ver
5146       Everyone  Casual  June 21, 2017       4.0.0  4.0 and up

INSPECTING REVIEWS DATASET

<class 'pandas.DataFrame'>
RangeIndex: 64295 entries, 0 to 64294
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   App                     64295 non-null  str
 1   Translated_Review       37427 non-null  str
 2   Sentiment               37432 non-null  str
 3   Sentiment_Polarity      37432 non-null  float64
 4   Sentiment_Subjectivity  37432 non-null  float64
dtypes: float64(2), str(3)
memory usage: 2.5 MB
None
                  App                                  Translated_Review  \
3636  Account Manager  Waste time. To take full advantage must retail...

     Sentiment  Sentiment_Polarity  Sentiment_Subjectivity
3636  Positive              0.1025                    0.36

In [6]:
# ANALYZING VALUES IN COLUMNS
print(apps.describe())
print(reviews.describe())

apps.describe(include='object')

            Rating
count  9367.000000
mean      4.193338
std       0.537431
min       1.000000
25%       4.000000
50%       4.300000
75%       4.500000
max      19.000000
       Sentiment_Polarity  Sentiment_Subjectivity
count        37432.000000            37432.000000
mean             0.182146                0.492704
std              0.351301                0.259949
min             -1.000000                0.000000
25%              0.000000                0.357143
50%              0.150000                0.514286
75%              0.400000                0.650000
max              1.000000                1.000000

,App,Category,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
count,10841,10841,10841,10841,10841,10840,10841,10840,10841,10841,10833,10838
unique,9660,34,6002,462,22,3,93,6,120,1378,2832,33
top,ROBLOX,FAMILY,0,Varies with device,"1,000,000+",Free,0,Everyone,Tools,"August 3, 2018",Varies with device,4.1 and up
freq,9,1972,596,1695,1579,10039,10040,8714,842,326,1459,2451

Max Rating = 19 should not be there. It is incorrect value since rating is on a 0-5 scale.

In [ ]:
# DATASET QUALITY ASSESSMENT
print('COUNT OF NULL ELEMENTS IN APP DATASET\n',apps.isna().sum())
print('\nCOUNT OF DUPLICATE ELEMENTS IN APP DATASET\n',apps.duplicated().sum())

print('\nCOUNT OF NULL ELEMENTS IN REVIEWS DATASET\n',reviews.isna().sum())
print('\nCOUNT OF DUPLICATE ELEMENTS IN REVIEWS DATASET\n',reviews.duplicated().sum())

COUNT OF NULL ELEMENTS IN APP DATASET
 App                  0
Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64

COUNT OF DUPLICATE ELEMENTS IN APP DATASET
 483

COUNT OF NULL ELEMENTS IN REVIEWS DATASET
 App                           0
Translated_Review         26868
Sentiment                 26863
Sentiment_Polarity        26863
Sentiment_Subjectivity    26863
dtype: int64

COUNT OF DUPLICATE ELEMENTS IN REVIEWS DATASET
 33616

<StringArray>
[             '1.0.0',              '2.0.0',              '1.2.4',
 'Varies with device',                '1.1',                '1.0',
           '6.1.61.1',              '2.9.2',                '2.8',
              '1.0.4',
 ...
           '3.20.001',             '1.3.81',               '1.74',
            '1.9.734',               '1.72',               '6.04',
            '1.5.447',         '1.0.612928',              '0.3.4',
          '2.0.148.0']
Length: 2833, dtype: str

In [ ]:
# UNIQUE ELEMENTS IN COLUMNS
print('UNIQUE ELEMENTS IN APP DATASET\n\nCATEGORY COLUMN\n',apps['Category'].unique())
print('\nRATING COLUMN\n',apps['Rating'].unique())
print('\nCONTENT RATING COLUMN\n',apps['Content Rating'].unique())
print('\nTYPE COLUMN\n',apps['Type'].unique())
print('\nANDROID VERSION COLUMN\n',apps['Android Ver'].unique())
print('\nCURRENT VERSION COLUMN\n',apps['Current Ver'].unique())

UNIQUE ELEMENTS IN APP DATASET

CATEGORY COLUMN
 <StringArray>
[     'ART_AND_DESIGN',   'AUTO_AND_VEHICLES',              'BEAUTY',
 'BOOKS_AND_REFERENCE',            'BUSINESS',              'COMICS',
       'COMMUNICATION',              'DATING',           'EDUCATION',
       'ENTERTAINMENT',              'EVENTS',             'FINANCE',
      'FOOD_AND_DRINK',  'HEALTH_AND_FITNESS',      'HOUSE_AND_HOME',
  'LIBRARIES_AND_DEMO',           'LIFESTYLE',                'GAME',
              'FAMILY',             'MEDICAL',              'SOCIAL',
            'SHOPPING',         'PHOTOGRAPHY',              'SPORTS',
    'TRAVEL_AND_LOCAL',               'TOOLS',     'PERSONALIZATION',
        'PRODUCTIVITY',           'PARENTING',             'WEATHER',
       'VIDEO_PLAYERS',  'NEWS_AND_MAGAZINES', 'MAPS_AND_NAVIGATION',
                 '1.9']
Length: 34, dtype: str

RATING COLUMN
 [ 4.1  3.9  4.7  4.5  4.3  4.4  3.8  4.2  4.6  3.2  4.   nan  4.8  4.9
  3.6  3.7  3.3  3.4  3.5  3.1  5.   2.6  3.   1.9  2.5  2.8  2.7  1.
  2.9  2.3  2.2  1.7  2.   1.8  2.4  1.6  2.1  1.4  1.5  1.2 19. ]

CONTENT RATING COLUMN
 <StringArray>
[        'Unrated',            'Teen',      'Mature 17+',    'Everyone 10+',
        'Everyone', 'Adults only 18+',               nan]
Length: 7, dtype: str

TYPE COLUMN
 <StringArray>
['Free', 'Paid', nan, '0']
Length: 4, dtype: str

ANDROID VERSION COLUMN
 <StringArray>
[      '4.0.3 and up',         '4.2 and up',         '4.4 and up',
         '2.3 and up',         '3.0 and up',         '4.1 and up',
         '4.0 and up',       '2.3.3 and up', 'Varies with device',
         '2.2 and up',         '5.0 and up',         '6.0 and up',
         '1.6 and up',         '1.5 and up',         '2.1 and up',
         '7.0 and up',         '5.1 and up',         '4.3 and up',
      '4.0.3 - 7.1.1',         '2.0 and up',         '3.2 and up',
        '4.4W and up',         '7.1 and up',        '7.0 - 7.1.1',
         '8.0 and up',          '5.0 - 8.0',         '3.1 and up',
       '2.0.1 and up',        '4.1 - 7.1.1',                  nan,
          '5.0 - 6.0',         '1.0 and up',        '2.2 - 7.1.1',
        '5.0 - 7.1.1']
Length: 34, dtype: str

CURRENT VERSION COLUMN
 <StringArray>
[             '1.0.0',              '2.0.0',              '1.2.4',
 'Varies with device',                '1.1',                '1.0',
           '6.1.61.1',              '2.9.2',                '2.8',
              '1.0.4',
 ...
           '3.20.001',             '1.3.81',               '1.74',
            '1.9.734',               '1.72',               '6.04',
            '1.5.447',         '1.0.612928',              '0.3.4',
          '2.0.148.0']
Length: 2833, dtype: str

1. Inconsistent Categories
    apps[Type] has Free, Paid, nan, 0
    No need for Free and 0, that can be combined into one

    Content Rating values need to be uniform

2. Inaccurate datatype in Apps dataset
    Reviews, installs should be int
    Price should be float
    Last Updated should be dt
    Price has $ in values, so that needs to be removed

3. Duplicate applications, which ones to drop

4. Missing ratings and Missing Android version, drop or to replace?

5. Incorrect values in rating column in app dataset