### CLEANING APPS DATASET
#### Process
1. Removing duplicates
2. Modifying data types of columns
3. Handling null values

In [ ]:
import pandas as pd
import numpy as np
apps = pd.read_csv('../datasets/apps.csv')
reviews = pd.read_csv('../datasets/reviews.csv')

In [ ]:
# ANALYZING DUPLICATE ROWS
# duplicate rows
apps[apps.duplicated()].sort_values(['App', 'Last Updated'])

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
1407,10 Best Foods for You,HEALTH_AND_FITNESS,4.0,2490,3.8M,"500,000+",Free,0,Everyone 10+,Health & Fitness,"February 17, 2017",1.9,2.3.3 and up
2543,1800 Contacts - Lens Store,MEDICAL,4.7,23160,26M,"1,000,000+",Free,0,Everyone,Medical,"July 27, 2018",7.4.1,5.0 and up
2385,2017 EMRA Antibiotic Guide,MEDICAL,4.4,12,3.8M,"1,000+",Paid,$16.99,Everyone,Medical,"January 27, 2017",1.0.5,4.0.3 and up
1434,21-Day Meditation Experience,HEALTH_AND_FITNESS,4.4,11506,15M,"100,000+",Free,0,Everyone,Health & Fitness,"August 2, 2018",3.0.0,4.1 and up
7035,420 BZ Budeze Delivery,MEDICAL,5.0,2,11M,100+,Free,0,Mature 17+,Medical,"June 6, 2018",1.0.1,4.1 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3014,"theScore: Live Sports Scores, News, Stats & Vi...",SPORTS,4.4,133825,34M,"10,000,000+",Free,0,Everyone 10+,Sports,"July 25, 2018",6.17.2,4.4 and up
3063,"theScore: Live Sports Scores, News, Stats & Vi...",SPORTS,4.4,133833,34M,"10,000,000+",Free,0,Everyone 10+,Sports,"July 25, 2018",6.17.2,4.4 and up
3085,"theScore: Live Sports Scores, News, Stats & Vi...",SPORTS,4.4,133833,34M,"10,000,000+",Free,0,Everyone 10+,Sports,"July 25, 2018",6.17.2,4.4 and up
3118,trivago: Hotels & Travel,TRAVEL_AND_LOCAL,4.2,219848,Varies with device,"50,000,000+",Free,0,Everyone,Travel & Local,"August 2, 2018",Varies with device,Varies with device
3202,trivago: Hotels & Travel,TRAVEL_AND_LOCAL,4.2,219848,Varies with device,"50,000,000+",Free,0,Everyone,Travel & Local,"August 2, 2018",Varies with device,Varies with device

In [ ]:
# REMOVING DUPLICATES

# dropping the duplicate rows and only keeping the last row of the dataset sorted by reviews
apps = apps.sort_values('Reviews').drop_duplicates(subset=['App'], keep='last')

apps.duplicated().sum()

App
Category
Rating            0.0
Reviews
Size
Installs
Type
Price
Content Rating
Genres
Last Updated
Current Ver
Android Ver
dtype: object

In [53]:
# CONVERTING DATA TYPES TO DESIRED DATA TYPES

print('Numeric Values Counts in Reviews')
print(apps['Reviews'].str.isnumeric().value_counts())
# so one row has non numeric review

print(apps[apps['Reviews'].str.isnumeric() == False])
# on inspection this row is malformed so we need to drop this

apps = apps[apps['Reviews'].str.isnumeric()]

print('\n\nNumeric Values Counts in Reviews')
print(apps['Reviews'].str.isnumeric().value_counts())

#now all rows in Reviews have numeric values and can be converted to int
apps['Reviews'] = apps['Reviews'].astype(int)

Numeric Values Counts in Reviews
Reviews
True     9659
False       1
Name: count, dtype: int64
                                           App Category  Rating Reviews  \
10472  Life Made WI-Fi Touchscreen Photo Frame      1.9    19.0    3.0M

         Size Installs Type     Price Content Rating             Genres  \
10472  1,000+     Free    0  Everyone            NaN  February 11, 2018

      Last Updated Current Ver Android Ver
10472       1.0.19  4.0 and up         NaN


Numeric Values Counts in Reviews
Reviews
True    9659
Name: count, dtype: int64

During data validation, one record was found with a non-numeric value in the Reviews column. Inspection showed that the entire row was malformed due to a column misalignment rather than a simple formatting issue. Since the record could not be reliably corrected, it was removed from the dataset.

In [54]:
#CONVERTING ALL VALUES IN INSTALLS COLUMN TO NUMERIC VALUES

clean_installs = (
    apps['Installs']
        .str.replace(',', '', regex=False)
        .str.replace('+', '', regex=False)
)

print('Rows with numeric values in Installs\n',clean_installs.str.isnumeric().value_counts())

# since all rows are numeric, data type of Installs can be changed

# Clean Installs
apps['Installs'] = (
    apps['Installs']
        .str.replace(',', '', regex=False)
        .str.replace('+', '', regex=False)
        .astype(int)
)

Rows with numeric values in Installs
 Installs
True    9659
Name: count, dtype: int64

In [61]:
# CONVERTING PRICE TO FLOAT
apps['Price'].unique()

apps['Price'].str.replace('$','').unique()

apps['Price'] = apps['Price'].str.replace('$','')

apps['Price'] = apps['Price'].astype(float)

In [64]:
apps['Last Updated'] = pd.to_datetime(
    apps['Last Updated'],
    format='%B %d, %Y'
)

In [65]:
apps.info()

<class 'pandas.DataFrame'>
Index: 9659 entries, 5499 to 2989
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             9659 non-null   str
 1   Category        9659 non-null   str
 2   Rating          8196 non-null   float64
 3   Reviews         9659 non-null   int64
 4   Size            9659 non-null   str
 5   Installs        9659 non-null   int64
 6   Type            9658 non-null   str
 7   Price           9659 non-null   float64
 8   Content Rating  9659 non-null   str
 9   Genres          9659 non-null   str
 10  Last Updated    9659 non-null   datetime64[us]
 11  Current Ver     9651 non-null   str
 12  Android Ver     9657 non-null   str
dtypes: datetime64[us](1), float64(2), int64(2), str(8)
memory usage: 1.0 MB

In [66]:
apps.isna().sum()

App                  0
Category             0
Rating            1463
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       0
Genres               0
Last Updated         0
Current Ver          8
Android Ver          2
dtype: int64

In [ ]:
# Analyzing null Rating values
apps[apps['Rating'].isna()]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
5499,AQ SMS Notify,TOOLS,NaN,0,2.3M,10,Free,0.00,Everyone,Tools,2018-04-12,2.5.3,4.1 and up
6738,BS Chopper,GAME,NaN,0,41M,100,Free,0.00,Everyone,Racing,2017-10-05,1.0,4.1 and up
4177,G-NetReport Pro,TOOLS,NaN,0,1.6M,10,Paid,25.99,Everyone,Tools,2018-06-14,5.0,4.0 and up
6399,Of the wall Arapaho bk,COMMUNICATION,NaN,0,12M,5,Free,0.00,Everyone,Communication,2017-08-18,1.0,4.1 and up
9532,Ek-yatri: Travel where you Belong,TRAVEL_AND_LOCAL,NaN,0,29M,1,Free,0.00,Everyone,Travel & Local,2018-08-01,1.0.0,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1177,Easy and Fast Recipes,FOOD_AND_DRINK,NaN,95,12M,50000,Free,0.00,Everyone,Food & Drink,2018-01-06,3.0.1,2.3 and up
9834,Recettes Faciles et Rapides,FOOD_AND_DRINK,NaN,95,12M,50000,Free,0.00,Everyone,Food & Drink,2018-01-06,3.0.1,2.3 and up
10818,Gold Quote - Gold.fr,FINANCE,NaN,96,1.5M,10000,Free,0.00,Everyone,Finance,2016-05-19,2.3,2.2 and up
10808,lesparticuliers.fr,LIFESTYLE,NaN,96,1.0M,50000,Free,0.00,Everyone,Lifestyle,2014-11-25,1.5,2.3 and up
3621,Voice Tables - no internet,PARENTING,NaN,970,71M,100000,Free,0.00,Everyone,Parenting,2018-05-28,2.0,4.0.3 and up

In [ ]:
# exploring statistics of reviews on basis of null ratings

print('No Ratings\n',apps.loc[apps['Rating'].isna(), 'Reviews'].describe())
print('\nWith Ratings\n',apps.loc[apps['Rating'].notna(), 'Reviews'].describe())

apps.loc[apps['Rating'].isna(), 'Reviews'].value_counts()

No Ratings
 count    1463.000000
mean       18.129870
std       140.427974
min         0.000000
25%         0.000000
50%         1.000000
75%         5.000000
max      3248.000000
Name: Reviews, dtype: float64

With Ratings
 count    8.196000e+03
mean     2.552483e+05
std      1.985679e+06
min      1.000000e+00
25%      1.260000e+02
50%      3.004000e+03
75%      4.371950e+04
max      7.815831e+07
Name: Reviews, dtype: float64

Reviews
0      593
1      205
2      131
3       94
4       63
      ...
83       1
86       1
91       1
94       1
970      1
Name: count, Length: 100, dtype: int64

In [75]:
apps.dropna(subset=['Rating'], inplace=True)

### Handling Missing Ratings

The missing values in the `Rating` column were investigated before applying any imputation technique.

Analysis showed that applications without ratings had a median of only 1 review, whereas applications with ratings had a median of 3,004 reviews. Additionally, over 40% of the unrated apps had zero reviews.

This indicates that the missing ratings are not random; rather, these applications had not received enough user feedback to generate a rating. Therefore, imputing missing ratings with the mean or median would introduce artificial values and bias the analysis.

To preserve data quality, rows with missing ratings were removed.

In [83]:
print(apps.isna().sum())

App               0
Category          0
Rating            0
Reviews           0
Size              0
Installs          0
Type              0
Price             0
Content Rating    0
Genres            0
Last Updated      0
Current Ver       4
Android Ver       2
dtype: int64

In [88]:
apps.loc[apps['Current Ver'].isna() | apps['Android Ver'].isna(),  ['App', 'Current Ver', 'Android Ver', 'Category', 'Rating', 'Reviews', 'Installs']]

,App,Current Ver,Android Ver,Category,Rating,Reviews,Installs
7333,Dots puzzle,NaN,4.0 and up,FAMILY,4.0,179,50000
4490,Pi Dark [substratum],1.1,NaN,PERSONALIZATION,4.5,189,10000
1553,Market Update Helper,NaN,1.5 and up,LIBRARIES_AND_DEMO,4.1,20145,1000000
4453,[substratum] Vacuum: P,4.4,NaN,PERSONALIZATION,4.4,230,1000
6322,Virtual DJ Sound Mixer,NaN,4.0 and up,TOOLS,4.2,4010,500000
15,Learn To Draw Kawaii Characters,NaN,4.2 and up,ART_AND_DESIGN,3.2,55,5000

The Current Ver and Android Ver columns contained only 4 and 2 missing values respectively. Since these columns were not central to the subsequent analyses and reliable values could not be inferred, the missing values were retained to avoid introducing inaccurate information.

In [94]:
apps.to_csv('cleaned_apps.csv', index=False)

In [97]:
df = pd.read_csv('cleaned_apps.csv')
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 8196 entries, 0 to 8195
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             8196 non-null   str
 1   Category        8196 non-null   str
 2   Rating          8196 non-null   float64
 3   Reviews         8196 non-null   int64
 4   Size            8196 non-null   str
 5   Installs        8196 non-null   int64
 6   Type            8196 non-null   str
 7   Price           8196 non-null   float64
 8   Content Rating  8196 non-null   str
 9   Genres          8196 non-null   str
 10  Last Updated    8196 non-null   str
 11  Current Ver     8192 non-null   str
 12  Android Ver     8194 non-null   str
dtypes: float64(2), int64(2), str(9)
memory usage: 832.5 KB

            Rating       Reviews      Installs        Price
count  8196.000000  8.196000e+03  8.196000e+03  8196.000000
mean      4.173084  2.552483e+05  9.168273e+06     1.037884
std       0.536522  1.985679e+06  5.825270e+07    16.857882
min       1.000000  1.000000e+00  1.000000e+00     0.000000
25%       4.000000  1.260000e+02  1.000000e+04     0.000000
50%       4.300000  3.004000e+03  1.000000e+05     0.000000
75%       4.500000  4.371950e+04  1.000000e+06     0.000000
max       5.000000  7.815831e+07  1.000000e+09   400.000000