### CLEANING REVIEWS DATASET
#### Process
    1. Analyzing and removing null values
    2. Analyzing duplicate values and deciding whether to drop or keep them
    3. Checking the quality of data in each column

In [1]:
import pandas as pd

In [ ]:
reviews = pd.read_csv('../datasets/reviews.csv')

In [32]:
# if there is no review, then there is no point of sentiment analysis or any other column
reviews.loc[lambda x : x['Translated_Review'].isna()].head(10)
reviews.loc[lambda x : x['Translated_Review'].isna()].tail(10)

,App,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity
64285,Houzz Interior Design Ideas,NaN,NaN,NaN,NaN
64286,Houzz Interior Design Ideas,NaN,NaN,NaN,NaN
64287,Houzz Interior Design Ideas,NaN,NaN,NaN,NaN
64288,Houzz Interior Design Ideas,NaN,NaN,NaN,NaN
64289,Houzz Interior Design Ideas,NaN,NaN,NaN,NaN
64290,Houzz Interior Design Ideas,NaN,NaN,NaN,NaN
64291,Houzz Interior Design Ideas,NaN,NaN,NaN,NaN
64292,Houzz Interior Design Ideas,NaN,NaN,NaN,NaN
64293,Houzz Interior Design Ideas,NaN,NaN,NaN,NaN
64294,Houzz Interior Design Ideas,NaN,NaN,NaN,NaN

In [ ]:
# REMOVING NULL REVIEWS
reviews = reviews.dropna(subset=['Translated_Review'])
print('Null values\n',reviews.isna().sum())
# so null values successfully removed
print('\nNon-null rows :\t',reviews.shape[0])

Null values
 App                       0
Translated_Review         0
Sentiment                 0
Sentiment_Polarity        0
Sentiment_Subjectivity    0
dtype: int64

Non-null rows :	 37427

In [ ]:
# REMOVING DUPLICATES

reviews[reviews.sort_values(by=['App','Translated_Review']).duplicated(subset=['App', 'Translated_Review'], keep=False)].tail(6)

# since mulitple users can give the same review, i wont drop duplicates

C:\Users\USER\AppData\Local\Temp\ipykernel_8200\293076119.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  reviews[reviews.sort_values(by=['App','Translated_Review']).duplicated(subset=['App', 'Translated_Review'], keep=False)].tail(6)

,App,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity
64071,Hotels.com: Book Hotel Rooms & Find Vacation D...,Made account using Google account. No option G...,Negative,-0.500000,0.500000
64073,Hotels.com: Book Hotel Rooms & Find Vacation D...,The new system showing Top 10 whole search res...,Negative,-0.032727,0.670909
64075,Hotels.com: Book Hotel Rooms & Find Vacation D...,Mobile currently crashing. Their international...,Neutral,0.000000,0.200000
64112,Hotspot Shield Free VPN Proxy & Wi-Fi Security,Good,Positive,0.700000,0.600000
64113,Hotspot Shield Free VPN Proxy & Wi-Fi Security,Good,Positive,0.700000,0.600000
64114,Hotspot Shield Free VPN Proxy & Wi-Fi Security,Good,Positive,0.700000,0.600000

In [54]:
#CHECKING QUALITY OF VALUES IN EACH COLUMN
print('Values in Sentiment Column\n',reviews['Sentiment'].unique(),'\n')
print('Checking Quality of Values in Sentiment Polarity and Sentiment Subjectivity Column')
reviews.agg({'Sentiment_Polarity':['min','max','mean'], 'Sentiment_Subjectivity':['min','max','mean']})

Values in Sentiment Column
 <StringArray>
['Positive', 'Neutral', 'Negative']
Length: 3, dtype: str

Checking Quality of Values in Sentiment Polarity and Sentiment Subjectivity Column

      Sentiment_Polarity  Sentiment_Subjectivity
min            -1.000000                 0.00000
max             1.000000                 1.00000
mean            0.182171                 0.49277

In [55]:
reviews.to_csv('cleaned_reviews.csv', index=False)

In [60]:
df = pd.read_csv('cleaned_reviews.csv')
df.info()
print('\n',df.isna().sum())
df.head()

<class 'pandas.DataFrame'>
RangeIndex: 37427 entries, 0 to 37426
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   App                     37427 non-null  str
 1   Translated_Review       37427 non-null  str
 2   Sentiment               37427 non-null  str
 3   Sentiment_Polarity      37427 non-null  float64
 4   Sentiment_Subjectivity  37427 non-null  float64
dtypes: float64(2), str(3)
memory usage: 1.4 MB

 App                       0
Translated_Review         0
Sentiment                 0
Sentiment_Polarity        0
Sentiment_Subjectivity    0
dtype: int64

,App,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity
0,10 Best Foods for You,I like eat delicious food. That's I'm cooking ...,Positive,1.00,0.533333
1,10 Best Foods for You,This help eating healthy exercise regular basis,Positive,0.25,0.288462
2,10 Best Foods for You,Works great especially going grocery store,Positive,0.40,0.875000
3,10 Best Foods for You,Best idea us,Positive,1.00,0.300000
4,10 Best Foods for You,Best way,Positive,1.00,0.300000